### ISSUE TITLE
Add expense / advance : form fields display unexpected errors

### ISSUE THREAD

**Issue by nilscox** [Bopzor/expenses#1]
Ay ay cap'tain!

On the add expense (or advance) forms, all the fields are in error state when backspacing some characters on an input.

**Steps to reproduce**

- open the app
- click on the "description" field
- type some characters

**Expected behavior**

The other fields should not display any error.

**Actual behavior**

The `coast` and `buyer` fields show some error messages ("This field is required" and "You must select one buyer" respectively).

**Version information**

Galaxy A3, Android 8. Please ask if you need more information.

**Comment by Bopzor** [comment]
Thank you for reporting.

It was working like that because I used to validate each field on input change (didn't matter which).

Now, front validation is more specific ! (fix in this [commit](https://github.com/Bopzor/expenses/commit/32fc450d0cade77f6ade8d58331468604d6609f1#diff-088e574137fd949e70876759fa82d596))

You can update your app :).
